### ISSUE TITLE
Relay stopped working; `ReferenceError: targetUri is not defined` error with AP Announce activity into inbox

### ISSUE THREAD

**Issue by ltlapy** [kokonect-link/cherrypick#483]
### 💡 Summary

AP Inbox 로 들어오는 `Announce` activity가 `ReferenceError: targetUri is not defined` 오류와 함께 처리되지 않는 문제가 발생하고 있습니다.
릴레이가 게시물의 전파에 announce 액티비티를 사용하는 만큼, 릴레이로부터 오는 연합을 받지 못하고 inbox 큐가 쌓이고 있습니다.

### 🥰 Expected Behavior

`Announce` activity is accepted without problem

### 🤬 Actual Behavior

```
ReferenceError: targetUri is not defined
    at ApInboxService.announceNote (file:///cherrypick/packages/backend/built/core/activitypub/ApInboxService.js:308:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApInboxService.announce (file:///cherrypick/packages/backend/built/core/activitypub/ApInboxService.js:292:36)
    at async ApInboxService.performOneActivity (file:///cherrypick/packages/backend/built/core/activitypub/ApInboxService.js:176:20)
    at async ApInboxService.performActivity (file:///cherrypick/packages/backend/built/core/activitypub/ApInboxService.js:143:22)
    at async InboxProcessorService.process (file:///cherrypick/packages/backend/built/queue/processors/InboxProcessorService.js:187:28)
    at async Worker.processJob (/cherrypick/node_modules/.pnpm/bullmq@5.7.8/node_modules/bullmq/dist/cjs/classes/worker.js:441:28)
    at async Worker.retryIfFailed (/cherrypick/node_modules/.pnpm/bullmq@5.7.8/node_modules/bullmq/dist/cjs/classes/worker.js:630:24)
```

### 📝 Steps to Reproduce

* Join some relay and write a post in another server with same relay

### 💻 Frontend Environment

```markdown
* Server URL:
  * k.lapy.link (4.9.0)
  * m.keepy.moe (4.9.0)
  * mi.rerac.dev (4.10.0-beta.1)
```

### 🛰 Backend Environment (for server admin)

```markdown
<!--
* Installation Method or Hosting Service: docker compose
* CherryPick: 4.9.0
* Node: 
* PostgreSQL:
* Redis: 
* OS and Architecture: Oracle Linux wakaran
-->
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
`4.10.0-rc.3`에서 해당 문제를 해결한 커밋이 반영되었습니다!
아마 작동할거라 생각은 하지만.. 혹시 모르니 테스트 해보시는 쪽이 좋을 것 같아요..!
